name: Update SwiftKey APK

on:
  schedule:
    - cron: '0 0 * * 0'  # اجرای هفتگی در یکشنبه ساعت 00:00 به وقت UTC
  workflow_dispatch:      # امکان اجرای دستی

jobs:
  update-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download APK
      run: |
        echo "Downloading APK from Farsroid..."
        # لینک مستقیم فایل APK مربوط به مود v8a:
        APK_URL="https://www.farsroid.com/files/swiftkey-keyboard_v8a.apk"
        curl -L -o swiftkey.apk "$APK_URL"

    - name: Commit changes if APK updated
      id: commit_step
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add swiftkey.apk
        if ! git diff --cached --quiet; then
          git commit -m "Automatically updated SwiftKey APK"
          # استفاده از روش push با تعیین توکن
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          echo "updated=true" >> $GITHUB_OUTPUT
        else
          echo "No changes in APK file. Skipping commit."
          echo "updated=false" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      if: steps.commit_step.outputs.updated == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: swiftkey.apk
